###
# script to creat tree from timetree.org
# http://timetree.org/
###

## read species list in and export as .txt file
dat <-  read.csv("~/Desktop/brmstest results/trait_level_data.csv")

species <- dat$Species


write.table(species, file = "~/Downloads/species_list.txt", row.names = FALSE, col.names = FALSE, quote = FALSE)

# read in newick file generated by timetree.org
species_tree <- ape::read.tree("~/Downloads/species_list.nwk")

plot(species_tree)

species_mat <- ape::cophenetic.phylo(species_tree)

heatmap(species_mat)

